name: spomodoro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.0.9
  vector_math: ^2.1.0
  day_night_time_picker: ^1.0.1
  hovering: ^1.0.4
  audioplayers: ^0.18.3
  avatar_glow: ^2.0.1
  # flutter_vector_icons: ^1.0.0
  # dots_indicator: ^2.0.0
  animations: ^2.0.0
  shared_preferences: ^2.0.5
  auto_size_text: ^2.1.0
  #db
  # responsive_util: ^0.3.0
  font_awesome_flutter: ^8.12.0
  # get: ^3.26.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: any


  
# flutter_icons:
#   android: true
#   ios: true
#   windows: true
#   image_path: "assets/images/icon.png"

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  fonts:
    - family: facon
      fonts:
        - asset: assets/fonts/facon.ttf
          weight: 700
    - family: Pixel
      fonts:
        - asset: assets/fonts/Pixel.otf
          weight: 700
    - family: KeepCalm
      fonts:
        - asset: assets/fonts/KeepCalm.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/a.mp3
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


    # - family: Facon
  #     fonts:
  #       - asset: fonts/Facon.ttf
  #         weight:700
  # #       - asset: fonts/Schyler-Italic.ttf
  # #         style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
